FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

{%- if config.framework == "Flask" %}
CMD ["flask", "run", "--host=0.0.0.0"]
{%- else %}
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
{%- endif %}
